module.exports = {
  User: require('./User'),
  Shop: require('./Shop'),
  Membership: require('./Membership'),
  Sector: require('./Sector'),
  Client: require('./Client'),
  Order: require('./Order'),
  Employee: require('./Employee'),
  Subscription: require('./Subscription'),
  WebhookEvent: require('./WebhookEvent'),
  ServiceCatalog: require('./ServiceCatalog'),
  AccessoryCatalog: require('./AccessoryCatalog'),
  BrandCatalog: require('./BrandCatalog'),
  OrderCounter: require('./OrderCounter'),
  PlatformError: require('./PlatformError'),
  PlatformMailLog: require('./PlatformMailLog'),
  PlatformConfig: require('./PlatformConfig'),
  PlatformNotice: require('./PlatformNotice'),
};
